Repository TheresAFewConors/Sooty, pull requests merged in 2019-11, with the labels that each got.

#31 Cleaned up duplicate imports
  Sooty.py
Labels: Useful Fix

#34 [VT Hashing] fix bug where variable does not actually hold hash
  Sooty.py
Labels: Bug Fix

#33 Configuration of API keys split out to a separate file
  .gitignore
  Sooty.py
  example_config.yaml
  readmeimages/.gitignore
  requirements.txt
Labels: Useful Fix, enhancement
