Repository TheresAFewConors/Sooty, pull requests merged in 2019-12, with the labels that each got.

#35 Fixing a library issue and created a parser template
  .github/workflows/linting_check.yml
  Modules/__init__.py
  Sooty.py
Labels: Bug Fix, Useful Fix, enhancement

#40 fix a couple of typos, no other changes
  README.md
Labels: Documentation, Useful Fix

#38 Added Phishtank Support
  .gitignore
  Modules/phishtank.py
  Sooty.py
  example_config.yaml
  requirements.txt
Labels: Enhancement, Further Documentation Needed
