Repository TheresAFewConors/Sooty, pull requests merged in 2020-10, with the labels that each got.

#63 Adding Docker support
  .github/workflows/anchore-analysis.yml
  .github/workflows/codeql-analysis.yml
  Dockerfile
  README.md
Labels: Bug Fix, Enhancement

#66 Add Unfurl to Decoders section
  Sooty.py
  requirements.txt
Labels: Enhancement

#69 Debug errors in BadIP
  Sooty.py
Labels: Bug Fix

#67 Added options for URLScan results [New]
  Sooty.py
Labels: Code Improvement
